# Generated by Django 5.1.6 on 2025-02-12 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('resistance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecialAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_power', models.IntegerField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='create_creature.race')),
            ],
        ),
        migrations.CreateModel(
            name='Creature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_creature.race')),
                ('special_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='create_creature.specialability')),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='create_creature.stats')),
            ],
        ),
    ]
